/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import reto52.Producto;
import javax.swing.JOptionPane;

public class Productos extends javax.swing.JFrame {

    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
        Refrescar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_listaproductos = new javax.swing.JTable();
        jButton_consultar = new javax.swing.JButton();
        jButton_salir = new javax.swing.JButton();
        jTextField_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_temperatura = new javax.swing.JTextField();
        jTextField_valorbase = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton_agregar = new javax.swing.JButton();
        jButton_actualizar = new javax.swing.JButton();
        jButton_eliminar = new javax.swing.JButton();
        jButton_limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("         PRODUCTOS");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));

        jScrollPane1.setBackground(new java.awt.Color(153, 153, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable_listaproductos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_listaproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_listaproductos.setGridColor(new java.awt.Color(255, 255, 255));
        jTable_listaproductos.setSelectionBackground(new java.awt.Color(153, 204, 255));
        jTable_listaproductos.setShowHorizontalLines(true);
        jTable_listaproductos.setShowVerticalLines(true);
        jTable_listaproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_listaproductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_listaproductos);

        jButton_consultar.setBackground(new java.awt.Color(204, 204, 204));
        jButton_consultar.setText("Consultar");
        jButton_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_consultarActionPerformed(evt);
            }
        });

        jButton_salir.setBackground(new java.awt.Color(204, 204, 204));
        jButton_salir.setText("Salir");
        jButton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salirActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        jLabel3.setText("Nombre");

        jLabel4.setText("Temperatura");

        jTextField_temperatura.setToolTipText("");

        jLabel5.setText("Valor Base");

        jButton_agregar.setBackground(new java.awt.Color(204, 204, 204));
        jButton_agregar.setText("Grabar");
        jButton_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_agregarActionPerformed(evt);
            }
        });

        jButton_actualizar.setBackground(new java.awt.Color(204, 204, 204));
        jButton_actualizar.setText("Actualizar");
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });

        jButton_eliminar.setBackground(new java.awt.Color(204, 204, 204));
        jButton_eliminar.setText("Borrar");
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });

        jButton_limpiar.setBackground(new java.awt.Color(204, 204, 204));
        jButton_limpiar.setText("Limpiar");
        jButton_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_id)
                                .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField_valorbase, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_temperatura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_salir)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_consultar)
                                .addGap(32, 32, 32)
                                .addComponent(jButton_actualizar)
                                .addGap(31, 31, 31)
                                .addComponent(jButton_agregar)))
                        .addGap(29, 29, 29)
                        .addComponent(jButton_eliminar)
                        .addGap(41, 41, 41)
                        .addComponent(jButton_limpiar)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_valorbase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_agregar)
                    .addComponent(jButton_eliminar)
                    .addComponent(jButton_limpiar)
                    .addComponent(jButton_actualizar)
                    .addComponent(jButton_consultar))
                .addGap(48, 48, 48)
                .addComponent(jButton_salir)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_consultarActionPerformed
        Refrescar();
    }//GEN-LAST:event_jButton_consultarActionPerformed

    private void jButton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salirActionPerformed
       JOptionPane mimensaje = new JOptionPane();
        int option = mimensaje.showConfirmDialog(this,"¿Estás seguro de que quieres cerrar la aplicación?","Confirmación de cierre",mimensaje.YES_NO_OPTION, mimensaje.QUESTION_MESSAGE);
            if (option == JOptionPane.YES_OPTION)
            {
                System.exit(0);
            }
    }//GEN-LAST:event_jButton_salirActionPerformed

    private void jButton_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_agregarActionPerformed
         JOptionPane mimensaje = new JOptionPane();
        //Obtengo los valores de los elementos que dibuje en el formulario
        String miid = jTextField_id.getText();
        String minombre = jTextField_nombre.getText();
        double mitemperatura= Double.parseDouble(jTextField_temperatura.getText());
        double mivalorbase=Double.parseDouble(jTextField_valorbase.getText());
        //Creo el objeto cliente
        Producto miproducto = new Producto();
        //Asigno los atributos al objeto cliente
        miproducto.setId(miid);
        miproducto.setNombre(minombre);
        miproducto.setTemperatura(mitemperatura);
        miproducto.setValorBase(mivalorbase);
        //Llamo al metodo grabar cliente y controlo su funcionalidad
        if(miproducto.guardarProducto()==true)
        {
            mimensaje.showMessageDialog(this,"¡ El registro fue agregado exitosamente !","Confirmación de registro", mimensaje.INFORMATION_MESSAGE);
            Refrescar();
        }
        else
        {
            mimensaje.showMessageDialog(this,"¡ Error al registrar !","Error en el registro", mimensaje.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_agregarActionPerformed

    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed
        JOptionPane mimensaje = new JOptionPane();
        String miid = jTextField_id.getText();
        String minombre = jTextField_nombre.getText();
        double mitemperatura= Double.parseDouble(jTextField_temperatura.getText());
        double mivalorbase=Double.parseDouble(jTextField_valorbase.getText());
        Producto miproducto = new Producto();
        miproducto.setId(miid);
        miproducto.setNombre(minombre);
        miproducto.setTemperatura(mitemperatura);
        miproducto.setValorBase(mivalorbase);
     
        if(miproducto.actualizarProducto()==true)
        {
            mimensaje.showMessageDialog(this,"¡ El registro fue actualizado exitosamente !","Confirmación de actualización", mimensaje.INFORMATION_MESSAGE);
            Refrescar();
        }
        else
        {
            mimensaje.showMessageDialog(this,"¡ Error al actualizar !","Error en la actualización", mimensaje.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_actualizarActionPerformed

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed
        JOptionPane mimensaje = new JOptionPane();
        String miid = jTextField_id.getText();
        Producto miproducto = new Producto();
        miproducto.setId(miid);
        int option = mimensaje.showConfirmDialog(this,"¿Estás seguro de borrar el registro?","Confirmación de eliminación",mimensaje.YES_NO_OPTION, mimensaje.WARNING_MESSAGE);
        if (option == JOptionPane.YES_OPTION)
        {
            if(miproducto.borrarProducto()==true)
            {
                mimensaje.showMessageDialog(this,"¡ El registro fue eliminado exitosamente !","Confirmación de eliminación", mimensaje.INFORMATION_MESSAGE);
                Refrescar();
            }
            else
            {
                mimensaje.showMessageDialog(this,"¡ Error al eliminar !","Error en la eliminación", mimensaje.ERROR_MESSAGE);
            }    
        }
    }//GEN-LAST:event_jButton_eliminarActionPerformed

    private void jButton_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limpiarActionPerformed
     
       jTextField_id.setText("");
       jTextField_nombre.setText("");
       jTextField_temperatura.setText("");
       jTextField_valorbase.setText("");
    }//GEN-LAST:event_jButton_limpiarActionPerformed

    private void jTable_listaproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_listaproductosMouseClicked
        int itemactual = jTable_listaproductos.getSelectedRow();
       jTextField_id.setText(jTable_listaproductos.getValueAt(itemactual, 0).toString());
       jTextField_nombre.setText(jTable_listaproductos.getValueAt(itemactual, 1).toString());
       jTextField_temperatura.setText(jTable_listaproductos.getValueAt(itemactual, 2).toString());
       jTextField_valorbase.setText(jTable_listaproductos.getValueAt(itemactual, 3).toString());
    }//GEN-LAST:event_jTable_listaproductosMouseClicked
    public void Refrescar()
    {
       Object[][] misdatos = new Object[1][6];
       Object[] miscolumnas = {"ID","Nombre","Temperatura","Valor Base","Costo"};
       DefaultTableModel mimodelo = new DefaultTableModel();
       //Asigno las columnas de la tabla
       mimodelo.setColumnIdentifiers(miscolumnas);
       jTable_listaproductos.setModel(mimodelo);
       Producto miproducto = new Producto();
       List<Producto> misproductos = miproducto.listarProductos();
       for(Producto productoactual : misproductos)
       {
           misdatos[0][0] = productoactual.getId();
           misdatos[0][1] = productoactual.getNombre();
           misdatos[0][2] = productoactual.getTemperatura();
           misdatos[0][3] = productoactual.getValorBase();
           if (productoactual.getTemperatura()<20)
           {
               misdatos[0][4] = productoactual.getValorBase()*1.2;
           }
           else
           {
               misdatos[0][4] = productoactual.getValorBase()*1.1;
           }
           misdatos[0][4] =String.format("%.2f",misdatos[0][4]);
           mimodelo.addRow(misdatos[0]);
       }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_actualizar;
    private javax.swing.JButton jButton_agregar;
    private javax.swing.JButton jButton_consultar;
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JButton jButton_limpiar;
    private javax.swing.JButton jButton_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_listaproductos;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_temperatura;
    private javax.swing.JTextField jTextField_valorbase;
    // End of variables declaration//GEN-END:variables
}
